### ISSUE TITLE
[FTR] No login favorites feed

### ISSUE THREAD

**Issue by caissalover** [austinhuang0131/instagrabber#24]
Firstly, fantastic application. I use it to access insta without login just to browse pictures anonymously.

A feature like the following would be fantastic.
App would fetch a list of favorite accounts and hashtags(already here) added by user who hasn't logged in, fetch timestamps of images, sort them according to time and feed the initial 10(say) to the app. When user scrolls down, more can load. That would be awesome. It would almost be equivalent to browsing instagram content without login. If there are too many accounts, I suggest choosing accounts on random but I leave that to you.

Thanks for this app.

**Comment by austinhuang0131** [comment]
* GraphQL does not accept multiple user IDs and that means I cannot request many users or else I'll end up facing [Bibliogram's issue](https://git.sr.ht/~cadence/bibliogram-docs/tree/master/docs/Instagram%20rate%20limits.md).
* The current DB structure also does not store user IDs so that means I'll have to add another column in the database which means y'all need to migrate again.

> If there are too many accounts, I suggest choosing accounts on random but I leave that to you.

Could confuse people...

---

In general, if you know an app that can do it, reopen and let me know. Otherwise, this will just lead to IP bans and possibly this app getting the hammer

**Comment by ildar** [comment]
I have an idea :
1. Cache the viewed channels
2. Show requested mix feed from just the cached feeds
Bonus : (1) allows (theoretically) showing something offline

**Comment by austinhuang0131** [comment]
With the usage pattern I have observed (some people literally have 100+ accounts favourited!), the cache size would be way too large

**Comment by ildar** [comment]
1. Opt-in?
2. Restrict to a few recently viewed channels. Also it's anonymous users
only!
3. Bibliogram
<https://git.sr.ht/~cadence/bibliogram-docs/tree/master/docs/Instagram%20rate%20limits.md>
says
they do some caching so thumbnails may skip cashing.

What do you think?

**Comment by austinhuang0131** [comment]
Again, if the user already viewed the userpage then why is a feed even necessary

Also you probably didn't read it but Bibliogram doesn't cache thumbnails, instead they cache user data (user ID, username, full name, avatar, follower count, following count, etc.)

**Comment by ildar** [comment]
Indeed
😅💢

**Comment by vonpupp** [comment]
I second this proposal. My use case would be a replacement for Instagram instead of just downloading or manually enter to some profile. Some sort of newpipe where I could get my subscriptions aggregated into a feed (similar to RSS). In my case, I don't care much about other's profiles suggestions nor related tags. I think limits would be acceptable, maybe a background update feature could be a possibility. Just some thoughts.

**Comment by modelfe** [comment]
In reference to this and [#673](https://github.com/austinhuang0131/barinsta/issues/673) (closed), would it be be easier to implement this **with** a logged in account? 

I'm using the app only while logged in. Out of the hundreds of accounts I'm following, there are only about 20 favorites who I'd like to see in a feed.

**Comment by austinhuang0131** [comment]
@modelfe No, you could be banned for scrapeing (it does happen!)
